name: Run Script Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Runs at minute 0 of every hour (UTC)
  workflow_dispatch:     # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # or '3.13.0' when available
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Create credentials file
        run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json
        shell: bash
          
      - name: Run script
        run: python script.py
        
      - name: Clean up credentials
        run: rm -f credentials.json  # Remove credentials after run
